version: '2'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cyclosm
    deploy:
      resources:
        reservations:
          cpus: '10'
          memory: 16G
    depends_on:
      - db
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
  db:
    image: world-bike-map-tile-server-db
    build:
      context: .
      dockerfile: Dockerfile.db
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 6G
    ports:
      - "5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - THREADS=4
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGPASSWORD=renderer
    volumes:
      - osm-data:/var/lib/postgresql/data
  import:
    image: world-bike-map-tile-server-import
    build:
      context: .
      dockerfile: Dockerfile.import
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 6G
    volumes:
      - .:/cyclosm
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - CACHE=8000
      - THREADS=10
      - OSM2PGSQL_DATAFILE

volumes:
  osm-data:
    external: true
